### ISSUE TITLE
Reports aren't showing forecasts from teams that submit only 1-week forecasts

### ISSUE THREAD

**Issue by sbfnk** [covid19-forecast-hub-europe/covid19-forecast-hub-europe#1020]
E.g., in Italy

![image](https://user-images.githubusercontent.com/1156307/136206605-42d43b63-c083-48c8-bd0b-b10861cd4222.png)

Related to 

https://github.com/epiforecasts/scoringutils/issues/136

**Comment by Bisaloo** [comment]
Duplicate of #759?

(if so, let's keep this one open since you linked to the relevant scoringutils issue)

**Comment by sbfnk** [comment]
Yes, good spot.
