### ISSUE TITLE
Euro hub reference

### ISSUE THREAD

**Issue by kathsherratt** [covid19-forecast-hub-europe/covid19-forecast-hub-europe#1448]
It would be useful to specify a suggested reference for citing the hub (repo/website), possibly linked to a zenodo release of the repo. 

Examples:
- US hub ref https://github.com/reichlab/covid19-forecast-hub#citing-the-forecast-hub
- DE/PL hub ref https://github.com/KITmetricslab/covid19-forecast-hub-de#german-and-polish-covid-19-forecast-hub

**Comment by Bisaloo** [comment]
We should discuss what kind of situation could require a citation. 

In particular, if people want to cite the forecast data, it might be a good time to re-open #963. On the other hand, if they only want to mention the project exists, a generic zenodo release might be enough.

**Comment by Bisaloo** [comment]
Release artifacts should include a zipped version of the `data-processed` folder (without the schema files) so users can access the data directly without all the fluff around

**Comment by Bisaloo** [comment]
We now have weekly releases at https://doi.org/10.5281/zenodo.6401421.

TODO:

- add artifacts
- specify metadata via `.zenodo.json` and in particular, determine who should be listed in authors

**Comment by Bisaloo** [comment]
Hopefully solved by https://github.com/covid19-forecast-hub-europe/covid19-forecast-hub-europe/commit/a43880ea18b51c15acdf2bc62172665a9dde3ea1 :crossed_fingers:
