### ISSUE TITLE
Baseline missing for forecast date 2021-12-20

### ISSUE THREAD

**Issue by sbfnk** [covid19-forecast-hub-europe/covid19-forecast-hub-europe#1700]
Instead we have 2021-12-21-EuroCOVIDhub-baseline.csv - should this not cause a validation error?

This missing is causing some problems with some of the evaluations that are relative to the baseline. Can we re-run the 2021-12-20 version and add it to the repo?

**Comment by Bisaloo** [comment]
Re your first point: baseline is not validated but it probably should... Should I convert the workflow to submit a PR instead? It might also make sense to move it to https://github.com/covid19-forecast-hub-europe/covid19-forecast-hub-europe-submissions because it's a model among others after all.

**Comment by sbfnk** [comment]
Yes, I like this suggestion a lot.
