### ISSUE TITLE
Remove cells with less than 3 models in the "Ensemble details" table 

### ISSUE THREAD

**Issue by Bisaloo** [covid19-forecast-hub-europe/covid19-forecast-hub-europe#2104]
At the bottom in [the ensemble report](https://covid19forecasthub.eu/reports/model-report-EuroCOVIDhub-ensemble.html):

![image](https://user-images.githubusercontent.com/10783929/177551106-b0a9705b-d7c8-4943-a2d9-19e08c5cb273.png)

In this example, hospitalisations in Italy should not be shown with 1 since models with less than 3 models are not included in the ensemble (since https://github.com/covid19-forecast-hub-europe/covid19-forecast-hub-europe/pull/2040).

I see two ways to do this:

- add a column in the [`criteria/` tables](https://github.com/covid19-forecast-hub-europe/covid19-forecast-hub-europe/tree/main/code/ensemble/EuroCOVIDhub/criteria) to indicate that models concerning targets with less than 3 models are excluded from the ensemble.
- manually remove these models from the "Ensemble details" table in https://github.com/covid19-forecast-hub-europe/covid19-forecast-hub-europe/blob/main/code/reports/rmdchunks/nmodels-ensemble.Rmd. In we go this route, we should probably implement #2041 first.

**Comment by kathsherratt** [comment]
Completed by @sbfnk in [EuroForecastHub](https://github.com/covid19-forecast-hub-europe/EuroForecastHub/commit/14b43e2dc615c0c218748c65cc209ac83c6faa0e) and in this repo [here](https://github.com/covid19-forecast-hub-europe/covid19-forecast-hub-europe/blob/c630ffce907204117bfd8b51103b23f90ca6d620/code/ensemble/EuroCOVIDhub/create-weekly-ensemble.R#L29)
