### ISSUE TITLE
Data Refresh for MUNI-ARIMA covid cases forecast

### ISSUE THREAD

**Issue by rodarish** [covid19-forecast-hub-europe/covid19-forecast-hub-europe#2125]
Hi, what are the timelines for data refresh for the forecasts? The main reports page says "The reports get updated every Tuesday."
Would be helpful to know exactly when new data is available.

**Comment by Bisaloo** [comment]
Hi @rodarish, thanks for reaching out!

The latest data should be online now.

For your information:
- the model reports are updated Tuesday&Wednesday at 11.45am UTC
- the country reports are updated Sunday at 4pm UTC
- the [interactive visualisation](https://covid19forecasthub.eu/visualisation.html) is updated every day at 8am & 12am UTC

**Comment by rodarish** [comment]
Thanks Bisaloo. (the visual never loads btw)
