### ISSUE TITLE
itwm-dSEIR: data for Rhineland-Palentine rather than for Germany

### ISSUE THREAD

**Issue by mohring** [covid19-forecast-hub-europe/covid19-forecast-hub-europe#2357]
Dear colleagues,
yesterday, we first uploaded the wrong forecast (for Rhineland-Palentine rather than Germany). Then we tried to replace it by the right forecast for Germany. Neele has sent a corresponding merge request. However, it seems that this request has not been accepted, yet.

**Comment by kathsherratt** [comment]
Closing this issue after it was handled in #2354.
