### ISSUE TITLE
`${{ env.GITHUB_WORKFLOW }}` isn't working

### ISSUE THREAD

**Issue by jsoref** [covid19-forecast-hub-europe/covid19-forecast-hub-europe#2388]
You probably technically know this, but I'd like to call it out (and I'll probably reference this somewhere else):
#2358

Was probably created by one of the following:
https://cs.github.com/?scopeName=All+repos&scope=&q=repo%3Acovid19-forecast-hub-europe%2Fcovid19-forecast-hub-europe+%22GitHub+Action+is+failing%22

> repo:covid19-forecast-hub-europe/covid19-forecast-hub-europe "GitHub Action is failing"
> Showing 1 - 10 of 10 files found (in 56 milliseconds)
> Technology Preview[Give feedback](https://cs.github.com/?scopeName=All+repos&scope=&q=repo%3Acovid19-forecast-hub-europe%2Fcovid19-forecast-hub-europe+%22GitHub+Action+is+failing%22#)

[covid19-forecast-hub-europe/covid19-forecast-hub-europe](https://cs.github.com/covid19-forecast-hub-europe/covid19-forecast-hub-europe?q=repo%3Acovid19-forecast-hub-europe%2Fcovid19-forecast-hub-europe%20%22GitHub%20Action%20is%20failing%22) [‎.github/workflows/JHU.yml‎](https://cs.github.com/covid19-forecast-hub-europe/covid19-forecast-hub-europe/blob/83daeffdc26968ea4e0c6f572dc72d3fc74d800d/.github/workflows/JHU.yml?q=repo%3Acovid19-forecast-hub-europe%2Fcovid19-forecast-hub-europe+%22GitHub+Action+is+failing%22)
```workflow
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh issue create \
          --label bug \
          --title "${{ env.GITHUB_WORKFLOW }} GitHub Action is failing" \
          --body-file .github/action-issue-template.md
```

[covid19-forecast-hub-europe/covid19-forecast-hub-europe](https://cs.github.com/covid19-forecast-hub-europe/covid19-forecast-hub-europe?q=repo%3Acovid19-forecast-hub-europe%2Fcovid19-forecast-hub-europe%20%22GitHub%20Action%20is%20failing%22) [‎.github/workflows/release.yml‎](https://cs.github.com/covid19-forecast-hub-europe/covid19-forecast-hub-europe/blob/83daeffdc26968ea4e0c6f572dc72d3fc74d800d/.github/workflows/release.yml?q=repo%3Acovid19-forecast-hub-europe%2Fcovid19-forecast-hub-europe+%22GitHub+Action+is+failing%22)
```workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue create \
            --label bug \
            --title "${{ env.GITHUB_WORKFLOW }} GitHub Action is failing" \
            --body-file .github/action-issue-template.md
```
[covid19-forecast-hub-europe/covid19-forecast-hub-europe](https://cs.github.com/covid19-forecast-hub-europe/covid19-forecast-hub-europe?q=repo%3Acovid19-forecast-hub-europe%2Fcovid19-forecast-hub-europe%20%22GitHub%20Action%20is%20failing%22) [‎.github/workflows/reports-model.yml‎](https://cs.github.com/covid19-forecast-hub-europe/covid19-forecast-hub-europe/blob/83daeffdc26968ea4e0c6f572dc72d3fc74d800d/.github/workflows/reports-model.yml?q=repo%3Acovid19-forecast-hub-europe%2Fcovid19-forecast-hub-europe+%22GitHub+Action+is+failing%22)
```workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue create \
            --label bug \
            --title "${{ env.GITHUB_WORKFLOW }} GitHub Action is failing" \
            --body-file .github/action-issue-template.md
```
[covid19-forecast-hub-europe/covid19-forecast-hub-europe](https://cs.github.com/covid19-forecast-hub-europe/covid19-forecast-hub-europe?q=repo%3Acovid19-forecast-hub-europe%2Fcovid19-forecast-hub-europe%20%22GitHub%20Action%20is%20failing%22) [‎.github/workflows/ensemble.yml‎](https://cs.github.com/covid19-forecast-hub-europe/covid19-forecast-hub-europe/blob/83daeffdc26968ea4e0c6f572dc72d3fc74d800d/.github/workflows/ensemble.yml?q=repo%3Acovid19-forecast-hub-europe%2Fcovid19-forecast-hub-europe+%22GitHub+Action+is+failing%22)
```workflow
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh issue create \
          --label bug \
          --title "${{ env.GITHUB_WORKFLOW }} GitHub Action is failing" \
          --body-file .github/action-issue-template.md
```
[covid19-forecast-hub-europe/covid19-forecast-hub-europe](https://cs.github.com/covid19-forecast-hub-europe/covid19-forecast-hub-europe?q=repo%3Acovid19-forecast-hub-europe%2Fcovid19-forecast-hub-europe%20%22GitHub%20Action%20is%20failing%22) [‎.github/workflows/scoring.yml‎](https://cs.github.com/covid19-forecast-hub-europe/covid19-forecast-hub-europe/blob/83daeffdc26968ea4e0c6f572dc72d3fc74d800d/.github/workflows/scoring.yml?q=repo%3Acovid19-forecast-hub-europe%2Fcovid19-forecast-hub-europe+%22GitHub+Action+is+failing%22)
```workflow
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh issue create \
          --label bug \
          --title "${{ env.GITHUB_WORKFLOW }} GitHub Action is failing" \
          --body-file .github/action-issue-template.md
```
[covid19-forecast-hub-europe/covid19-forecast-hub-europe](https://cs.github.com/covid19-forecast-hub-europe/covid19-forecast-hub-europe?q=repo%3Acovid19-forecast-hub-europe%2Fcovid19-forecast-hub-europe%20%22GitHub%20Action%20is%20failing%22) [‎.github/workflows/reports-country.yml‎](https://cs.github.com/covid19-forecast-hub-europe/covid19-forecast-hub-europe/blob/83daeffdc26968ea4e0c6f572dc72d3fc74d800d/.github/workflows/reports-country.yml?q=repo%3Acovid19-forecast-hub-europe%2Fcovid19-forecast-hub-europe+%22GitHub+Action+is+failing%22)
```workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue create \
            --label bug \
            --title "${{ env.GITHUB_WORKFLOW }} GitHub Action is failing" \
            --body-file .github/action-issue-template.md
```
[covid19-forecast-hub-europe/covid19-forecast-hub-europe](https://cs.github.com/covid19-forecast-hub-europe/covid19-forecast-hub-europe?q=repo%3Acovid19-forecast-hub-europe%2Fcovid19-forecast-hub-europe%20%22GitHub%20Action%20is%20failing%22) [‎.github/workflows/visualisation.yml‎](https://cs.github.com/covid19-forecast-hub-europe/covid19-forecast-hub-europe/blob/83daeffdc26968ea4e0c6f572dc72d3fc74d800d/.github/workflows/visualisation.yml?q=repo%3Acovid19-forecast-hub-europe%2Fcovid19-forecast-hub-europe+%22GitHub+Action+is+failing%22)
```workflow
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh issue create \
          --label bug \
          --title "${{ env.GITHUB_WORKFLOW }} GitHub Action is failing" \
          --body-file .github/action-issue-template.md
```
[covid19-forecast-hub-europe/covid19-forecast-hub-europe](https://cs.github.com/covid19-forecast-hub-europe/covid19-forecast-hub-europe?q=repo%3Acovid19-forecast-hub-europe%2Fcovid19-forecast-hub-europe%20%22GitHub%20Action%20is%20failing%22) [‎.github/workflows/zoltar-upload.yml‎](https://cs.github.com/covid19-forecast-hub-europe/covid19-forecast-hub-europe/blob/83daeffdc26968ea4e0c6f572dc72d3fc74d800d/.github/workflows/zoltar-upload.yml?q=repo%3Acovid19-forecast-hub-europe%2Fcovid19-forecast-hub-europe+%22GitHub+Action+is+failing%22)
```workflow
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh issue create \
          --label bug \
          --title "${{ env.GITHUB_WORKFLOW }} GitHub Action is failing" \
          --body-file .github/action-issue-template.md
```
[covid19-forecast-hub-europe/covid19-forecast-hub-europe](https://cs.github.com/covid19-forecast-hub-europe/covid19-forecast-hub-europe?q=repo%3Acovid19-forecast-hub-europe%2Fcovid19-forecast-hub-europe%20%22GitHub%20Action%20is%20failing%22) [‎.github/workflows/ECDC.yml‎](https://cs.github.com/covid19-forecast-hub-europe/covid19-forecast-hub-europe/blob/83daeffdc26968ea4e0c6f572dc72d3fc74d800d/.github/workflows/ECDC.yml?q=repo%3Acovid19-forecast-hub-europe%2Fcovid19-forecast-hub-europe+%22GitHub+Action+is+failing%22)
```workflow
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh issue create \
          --label bug \
          --title "${{ env.GITHUB_WORKFLOW }} GitHub Action is failing" \
          --body-file .github/action-issue-template.md
```
[covid19-forecast-hub-europe/covid19-forecast-hub-europe](https://cs.github.com/covid19-forecast-hub-europe/covid19-forecast-hub-europe?q=repo%3Acovid19-forecast-hub-europe%2Fcovid19-forecast-hub-europe%20%22GitHub%20Action%20is%20failing%22) [‎.github/workflows/check-truth.yml‎](https://cs.github.com/covid19-forecast-hub-europe/covid19-forecast-hub-europe/blob/83daeffdc26968ea4e0c6f572dc72d3fc74d800d/.github/workflows/check-truth.yml?q=repo%3Acovid19-forecast-hub-europe%2Fcovid19-forecast-hub-europe+%22GitHub+Action+is+failing%22)
```workflow
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh issue create \
          --label bug \
          --title "${{ env.GITHUB_WORKFLOW }} GitHub Action is failing" \
          --body-file .github/action-issue-template.md
```

**Comment by kathsherratt** [comment]
Thanks @jsoref. All workflows do now appear to be running fine so will close this issue.
