### ISSUE TITLE
Incidence of Hospitals in Slovenia are wrong 

### ISSUE THREAD

**Issue by janezz25** [covid19-forecast-hub-europe/covid19-forecast-hub-europe#2446]
Dear All,

We are observing some huge discrepancies on number of hospital admissions for Slovenia. The numbers should be at least a magnitude lower than these, which are shown in forecasts for Slovenia. 

Please see https://covid-19.sledilnik.org/en/stats under the plot Hospitalizations.

**Comment by sbfnk** [comment]
Thank you! This should be fixed now.
