### ISSUE TITLE
Use `yml` extension for metadata files

### ISSUE THREAD

**Issue by Bisaloo** [covid19-forecast-hub-europe/covid19-forecast-hub-europe#601]
Currently, metadata files must have the format `metadata-model.txt` but it looks like a YAML file and it's actually read using the `yaml` python library in the `validations` submodule.

Would it make sense to use the `yml` file extension instead?

Benefits:

1. We get syntax highlighting, which might help spotting syntax error. Below is an example where the user adds `:` without enclosing the string in quotes ( `source:` appears in brown):

![image](https://user-images.githubusercontent.com/10783929/124135503-62495780-da73-11eb-83f7-e478e875da66.png)

2. Users are explicitly allowed to use comments with the usual YAML syntax

**Comment by Bisaloo** [comment]
Lines to edit if we want to change this:

https://github.com/epiforecasts/covid19-forecast-hub-europe-validations/blob/31c2cffbc25bea944bdc184260e96aad4ea6cd27/main.py#L25

https://github.com/epiforecasts/covid19-forecast-hub-europe-validations/blob/31c2cffbc25bea944bdc184260e96aad4ea6cd27/main.py#L153

https://github.com/epiforecasts/covid19-forecast-hub-europe-validations/blob/31c2cffbc25bea944bdc184260e96aad4ea6cd27/main.py#L171

https://github.com/epiforecasts/covid19-forecast-hub-europe-validations/blob/31c2cffbc25bea944bdc184260e96aad4ea6cd27/main.py#L176

https://github.com/epiforecasts/covid19-forecast-hub-europe-validations/blob/31c2cffbc25bea944bdc184260e96aad4ea6cd27/codebase/validation_functions/metadata.py#L28

https://github.com/epiforecasts/covid19-forecast-hub-europe-validations/blob/31c2cffbc25bea944bdc184260e96aad4ea6cd27/codebase/validation_functions/metadata.py#L156

https://github.com/epiforecasts/covid19-forecast-hub-europe-validations/blob/31c2cffbc25bea944bdc184260e96aad4ea6cd27/codebase/validation_functions/metadata.py#L170

**Comment by sbfnk** [comment]
It would definitely be an improvement - only downside I can see is that if we rename all the metadata files then if teams work in a fork and never merge `main` (which I think is how teams operate in most cases) then if they ever change their metadata the corresponding PR can't be merged without them explicitly renaming the file. This might lead to some confusion.

That said, it's probably worth the benefit, and we could flag it to the teams so they're aware.

**Comment by Bisaloo** [comment]
What about scheduling this when the new validations package is out? The output / error message should hopefully be clearer and not confuse teams as much.

**Comment by Bisaloo** [comment]
Note to self: also use this opportunity to remove the `incomplete final line found` warning.
