### ISSUE TITLE
Consider splitting `target` in `target_variable` and `horizon` in forecasts

### ISSUE THREAD

**Issue by Bisaloo** [covid19-forecast-hub-europe/covid19-forecast-hub-europe#708]
This might not possible for the current iteration of the hub but I think it could be worthwhile to consider it for the next time. The current `target` column contains two pieces of information that would probably make more sense separated.

I started to think about it while trying to loop over `target_type` in the submission app to reduce code duplication:

https://github.com/epiforecasts/ForecastHubSubmissionApp/blob/efeec37c6781adf2349e407380e6cf0f9fb986b5/R/app_server.R#L96-L127

I also intuitively thought this was two different columns when I drafted the specs for the validation package:

> - test that horizons match horizons in the config file
> - test that target types match target types in the config file

Beyond the conceptual argument, this would make our lives easier for the downstream analyses where we always end up splitting this column in 2.

**Comment by sbfnk** [comment]
Very much agree that every column should contain exactly one piece of information: arguably `1 wk ahead inc case` contains 4 (1, wk, inc, wk) and "ahead" is redundant.

Two related questions are:
- which information to include: if `target_end_date` and `forecast date` are given then `1 wk ahead` is redundant but possibly useful for checking that this is interpreted as intended by the forecaster. 
- which information to include in file names and which to include in tables. My inclination would be to be independent of file names but including information there makes it easier to e.g. load only forecasts for certain dates without having to read in all files; it also reduces the amount of repetition affecting storage. Ultimately csv might not be the ideal format for this and it could be that eventually it's best handled by something more suitable like Zoltar or e.g. `json`.

**Comment by Bisaloo** [comment]
On a related note, if we split the columns, it would be worthwhile to spell out entire words: cases/deaths/hospitalizations, incident/cumulative. We always want to full word in visualizations & reports and the current approach of having a dictionary (hosp <-> hospitalizations, case <-> cases, etc.) does not allow for generalization to any target without code changes.

**Comment by Bisaloo** [comment]
It's too late to implement in the forecast hub but we agreed to add it to the standard with the data format working group including the other hubs.
