### ISSUE TITLE
Spell out target variables (cases, deaths, hospitalisations) in forecast csv

### ISSUE THREAD

**Issue by Bisaloo** [covid19-forecast-hub-europe/covid19-forecast-hub-europe#796]
### Spell out target variables (cases, deaths, hospitalizations) in forecast csv instead of abbreviated version

I already mentioned this in #789 and https://github.com/epiforecasts/covid19-forecast-hub-europe/issues/708#issuecomment-897915335 but I believe it deserves its own issue.

This is a serious hurdle to write and provide generalisable code where everything works directly by simply editing the config file.

I also wanted to open an issue to keep track of the places where we maintain a dictionary of terms from csv / beautiful names for plots:

https://github.com/epiforecasts/covid19-forecast-hub-europe/blob/e88f9525d3c3e40e617ee5858f8cced7179a5b05/viz/prepare_forecast_data.py#L106-L109

https://github.com/epiforecasts/covid19-forecast-hub-europe/blob/e88f9525d3c3e40e617ee5858f8cced7179a5b05/code/reports/rmdchunks/define-targets-horizons.Rmd#L11

**Comment by kathsherratt** [comment]
I agree in principle, here and with your and Seb's comments in #708. I think this should definitely be one of the points to consider if we have a wider discussion among the hubs about how we maintain compatibility (what and who for) in future.

For now one quick temporary helper might be to put a "short name" and "long name" for each target in the hub config?

**Comment by Bisaloo** [comment]
Comment by Nick: would this make the files significantly larger? This is relevant for the US hub where they have storage size issues.

**Comment by Bisaloo** [comment]
``` r
test_url<- "https://github.com/epiforecasts/covid19-forecast-hub-europe/raw/main/data-processed/EuroCOVIDhub-baseline/2021-12-13-EuroCOVIDhub-baseline.csv"
test_file <- tempfile(pattern = "orig", fileext = ".csv")
download.file(test_url, test_file)
```

# Original file

Original file size

``` r
(orig_filesize <- file.size(test_file))
#> [1] 493279
```

Size of object in memory

``` r
(orig_memsize <- as.numeric(lobstr::obj_size(read.csv(test_file))))
#> [1] 408976
```

The file size is exactly the total number of character in the file
(including `\n` which separates each line)

``` r
df <- readLines(test_file)
sum(nchar(df) + 1)
#> [1] 493279
```

# File with more columns

This means that if we change the spaces (`" "`) by commas (`","`), thus creating
new columns, the file size will remain exactly the same

``` r
library(tidyverse)
df <- read.csv(test_file)

header <- paste(colnames(df), collapse = ",")
output_multicols <- tempfile(pattern = "multicols", fileext = ".csv")

df_multicols <- df %>%
  tidyr::separate(target, c("horizon", "horizon_unit", "direction", "type", "target"))

df_multicols %>%
  write.csv(output_multicols, row.names = FALSE, quote = FALSE)

# It's even smaller????
(multicols_filesize <- file.size(output_multicols))
#> [1] 424298
```

The object is however slightly larger in memory

``` r
(multicols_memsize <- as.numeric(lobstr::obj_size(df_multicols)))
#> [1] 595600
```

# File with more columns spelling everything out

``` r
output_spell <- tempfile(pattern = "spell", fileext = ".csv")

df_spell <- df %>%
  tidyr::separate(target, c("horizon", "horizon_unit", "direction", "type", "target")) %>%
  dplyr::mutate(
    horizon_unit = "week",
    type = "increasing",
    target = dplyr::case_when(
      target == "case" ~ "cases",
      target == "death" ~ "deaths",
      target == "hosp" ~ "hospitalisations"
    ))

write.csv(df_spell, output_spell, row.names = FALSE, quote = FALSE)
```

The size in memoy is almost the same as when we don’t spell everything out
(because R objects in memory are actually compressed and each possible value
of a character is only stored once.

``` r
(spell_memsize <- as.numeric(lobstr::obj_size(df_spell)))
#> [1] 595632

(spell_filesize <- file.size(output_spell))
#> [1] 520010
```

# Summary

``` r
c(orig_filesize, orig_memsize,
  multicols_filesize, multicols_memsize,
  spell_filesize, spell_memsize) %>%
  matrix(
    ncol = 2, byrow = TRUE, 
    dimnames = list(c("orig", "multicols", "spell"), c("filesize", "memsize"))
  ) %>%
  knitr::kable()
```

|           | filesize | memsize |
|:----------|---------:|--------:|
| orig      |   493279 |  408976 |
| multicols |   424298 |  595600 |
| spell     |   520010 |  595632 |

<sup>Created on 2021-12-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by Bisaloo** [comment]
It's too late to implement in the forecast hub but we agreed to add it to the standard with the data format working group including the other hubs.
