### ISSUE TITLE
Calculation of hospitalisation data

### ISSUE THREAD

**Issue by sbfnk** [covid19-forecast-hub-europe/covid19-forecast-hub-europe#941]
At the moment our hospitalisation data is subject to a fair amount of retrospective revision.

In order to be consistent with the JHU data we're using what we should probably do instead is
1) compile a daily data set of cumulative number of hospitalisations per country
2) every week, take the Sunday-Sunday (or Saturday-Saturday) difference as weekly new number of hospitalisations.

**Comment by Bisaloo** [comment]
I have a script doing this for the data we recorded until now. But the results don't look so great. Especially because we have some gaps in the data (weekends?)

``` r
library(gh)
library(purrr)

get_all_versions <- function(file, gh_repo) {

  gh(
    "/repos/{gh_repo}/commits?path={file}",
    gh_repo = gh_repo,
    file = file
  ) %>%
    map_chr("sha") %>%
    map_chr(~ glue::glue(
      "https://raw.githubusercontent.com/{gh_repo}/{sha}/{file}",
      gh_repo = gh_repo,
      sha = .x,
      file = file
    )) %>%
    map_chr(utils::URLencode) %>%
    map(readr::read_csv, show_col_types = FALSE, progress = FALSE)

}

all_hospdata_versions <- get_all_versions(
  "data-truth/ECDC/truth_ECDC-Incident Hospitalizations.csv",
  "epiforecasts/covid19-forecast-hub-europe"
)

library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
adjusted_hospdata <- all_hospdata_versions %>%
  map(group_by, location) %>%
  map(arrange, date) %>%
  map(mutate, cum_value = cumsum(value), .keep = "unused") %>%
  map(filter, date == max(date)) %>%
  bind_rows() %>%
  distinct() %>%
  arrange(location, date) %>%
  mutate(value = cum_value - lag(cum_value))

adjusted_hospdata
#> # A tibble: 225 × 5
#> # Groups:   location [11]
#>    date       location location_name cum_value value
#>    <date>     <chr>    <chr>             <dbl> <dbl>
#>  1 2021-08-27 BE       Belgium           77587    NA
#>  2 2021-08-30 BE       Belgium           77758   171
#>  3 2021-08-31 BE       Belgium           77842    84
#>  4 2021-09-01 BE       Belgium           77909    67
#>  5 2021-09-02 BE       Belgium           77983    74
#>  6 2021-09-03 BE       Belgium           78044    61
#>  7 2021-09-06 BE       Belgium           78248   204
#>  8 2021-09-07 BE       Belgium           78333    85
#>  9 2021-09-08 BE       Belgium           78397    64
#> 10 2021-09-09 BE       Belgium           78459    62
#> # … with 215 more rows
library(ggplot2)
ggplot(adjusted_hospdata, aes(x = date, y = value)) +
  geom_line() +
  facet_wrap(vars(location_name), scales = "free_y")
#> Warning: Removed 2 row(s) containing missing values (geom_path).
```

![](https://i.imgur.com/LhyP26z.png)

<sup>Created on 2021-09-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by Bisaloo** [comment]
The problem is that we don't have any data upload during the weekend for some countries. They upload 3 days at once on Monday.

What should I do in this case? Take the data posted on Monday for the weekend?

In other words, the idea would be "always take the earliest known value for each day and then use it for the cumulative sum and diff".

@kathsherratt, @sbfnk

**Comment by sbfnk** [comment]
There's just been some new discussion about hospitalisation data and whether we can get a better data set - let's park this question for the moment.

**Comment by Bisaloo** [comment]
https://www.ecdc.europa.eu/en/publications-data/download-data-hospital-and-icu-admission-rates-and-current-occupancy-covid-19

**Comment by sbfnk** [comment]
Superseded by new data source in #2823
